[workspace]
members = [
    "core",
    "datatypes",
    "examples/websites",
    "examples/proto_counts",
    # "examples/filter_stats",
]
resolver = "2"

[profile.release]
lto = true

[patch.crates-io]
pcap = { git = 'https://github.com/thegwan/pcap', branch = 'compile-optimized' }

